---
# COCO 2017 dataset http://cocodataset.org
# Train command: python train.py --data coco.yaml
# Default dataset location is next to /yolov5:
#   /parent_folder
#     /coco
#     /yolov5

# download command/URL (optional)
# download: bash data/scripts/get_coco.sh

# train and val data as 1) directory: path/images/, 2)
# file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: /workspaces/OTLabels/data/prototype/train
val: /workspaces/OTLabels/data/prototype/val
test: /workspaces/OTLabels/data/prototype/test

# number of classes
nc: 18

# class names
names:
  [
    "pedestrian",
    "bicyclist",
    "bicyclist_with_trailer",
    "cargo_bike_driver",
    "scooter_driver",
    "motorcyclist",
    "car",
    "car_with_trailer",
    "private_van",
    "private_van_with_trailer",
    "delivery_van",
    "delivery_van_with_trailer",
    "truck",
    "truck_with_trailer",
    "bus",
    "train",
    "truck_with_semitrailer",
    "other",
  ]
# Print classes
# with open('data/coco.yaml') as f:
#   d = yaml.load(f, Loader=yaml.FullLoader)  # dict
#   for i, x in enumerate(d['names']):
#     print(i, x)
