from pathlib import Path

from OTLabels.images.copy_images import ImageSet, Site

output_path = Path("data/image_data")

input_path = Path("data/org")


set = [
    Site(
        name="Heiligenstadt-Leipzig_OTCamera01",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera02",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera04",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera05",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera06",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera07",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera08",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera09",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera10",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera11",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera13",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera15",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera16",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera17",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Heiligenstadt-Leipzig_OTCamera20",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="TUD_Dresden_Alaunstr_cam1",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="TUD_Dresden_Alaunstr_cam3",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="TUD_Dresden_Postplatz_cam2",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="TUD_Leipzig_cam1",
        input_path=Path(f"{input_path}/Armin"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera12",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera13",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera15",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera16",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera17",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera19",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Aachen_OTCamera20",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Jena_OTCameraJena01",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Jena_OTCameraJena02",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera01",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera02",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera03",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera04",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera07",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera08",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera13",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera14",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera15",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera16",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera17",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera18",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera19",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
    Site(
        name="Saarbruecken_OTCamera20",
        input_path=Path(f"{input_path}/Hendrik"),
        output_path=output_path,
    ),
]


ImageSet(set).copy()
